### ISSUE TITLE
True true TruE are treated same as 1b

### ISSUE THREAD

**Issue by ch-yx** [vberlier/nbtlib#13]
https://twitter.com/0x00716f62/status/1093232931521351681

**Comment by vberlier** [comment]
You're right seems like `true` and `false` are aliases for `1b` and `0b` respectively. I implemented that in edc9a30aac9508517ead478f024713036326c4fb.

**Comment by vberlier** [comment]
Okay this is now in release 1.4.3, closing the issue.
