### ISSUE TITLE
`File` is not writing the trailing End tag

### ISSUE THREAD

**Issue by MestreLion** [vberlier/nbtlib#153]
Now that you/we have "unwrapped" the spurious root Compound from `File`, it is now responsible to make sure the following are written:
- its own tag ID
- name (mostly empty, but still takes 2 bytes to say so)
- its children
- _the trailing End tag_

Writing the children and the End is done by `Compound.write()`, which correctly do so:
https://github.com/vberlier/nbtlib/blob/e8aa2895303a84f4fe97fb0f8a30fdbcd690b32c/nbtlib/tag.py#L1095

But... `self.end_tag` is overwritten in `File` to be...
https://github.com/vberlier/nbtlib/blob/e8aa2895303a84f4fe97fb0f8a30fdbcd690b32c/nbtlib/nbt.py#L213

With this justification:
```python
# We remove the inherited end tag as the end of nbt files is
# specified by the end of the file
end_tag = b""
```

This used to work when we had an extra Compound layer. Not anymore. And NBT Explorer, for example, _does_ require that trailing byte (it doesn't even _list_ the file if it doesn't have it), so perhaps Minecraft does too.

But, before filling this 1-line PR fix, I'd like to understand _why_ `File` had this setting in the first place (since the initial commit!). Was it _only_ a workaround _because_ of the extra layer, or does it has other roles? Is the justification in that comment really valid? Would it have any consequence or side effect in removing it, letting it fallback to Compoud's `b"\x00"`? Does `parse()` require it to be blank, perhaps for fault tolerance purposes?

Please investigate possible consequences and side effects of this before merging the PR! I would love to head some feedback from you.

**Comment by SmylerMC** [comment]
I can confirm that this change also breaks schematic created with Litemapy for Litematica (see the Github mention above). Decompressing the file, adding a trailing null byte and re-compressing it works and allows the file to load both in game with Litematica and in NBTExplorer.

**Comment by vberlier** [comment]
Oh right I didn't think about that, I was kind of in a rush sorry. I'm gonna try to go over all this in a few days. In the meantime I think the 2.x releases should be considered experimental and unstable.

**Comment by ch-yx** [comment]
>I'd like to understand why File had this setting in the first place

because mojang write that...
the file is some thing like that iirc:

tagtypeid lenofname name data
and no end tag after "data"
just like a len=1 compound without end. eg:
{"":data

that is why the File class set end_tag = b""

**Comment by MestreLion** [comment]
> > I'd like to understand why File had this setting in the first place
> 
> because mojang write that... the file is some thing like that iirc:
> 
> tagtypeid lenofname name data and no end tag after "data" just like a len=1 compound without end. eg: {"":data
> 
> that is why the File class set end_tag = b""

That is not accurate, at least not for recent versions of Minecraft: `level.dat`, all `map_*.dat` files including `idcounts.dat`, and also chunk data, they all have a trailing NUL byte. NBT Explorer does not even _show_ the file if it doesn't have the trailing byte, so likely Mojang does so from a long time.
