### ISSUE TITLE
Iterate NBT

### ISSUE THREAD

**Issue by epifeny** [vberlier/nbtlib#183]
Is it possible to iterate over the `nbtlib.tag.Compound` after `nbtlib.load`?

```python
>>> nbtfile = nbtlib.load("C:\\Users\\WDAGUtilityAccount\\Desktop\\level.dat")
>>> type(nbtfile['Data'])
<class 'nbtlib.tag.Compound'>
```

**Comment by ch-yx** [comment]
they are subclass of built in types. so yes since dicts are iterable

**Comment by epifeny** [comment]
> they are subclass of built in types. so yes since dicts are iterable

Thanks! Can you give me an example of how I do this? I'm kinda new to Python.

**Comment by ch-yx** [comment]
😳you should read some python guide for beginners.
for example, you can try
dict.keys(), dict.values() and dict.items()


by the way, if you list(a_dict) or for xxx in a_dict, it is short for list(a_dict.keys()) or for xxx in a_dict.keys()

**Comment by epifeny** [comment]
Thanks!
