### ISSUE TITLE
Jython compatibility

### ISSUE THREAD

**Issue by CptGummiball** [vberlier/nbtlib#196]
Is there any way to use nbtlib with Jython?
Unfortunately, Jython is currently only compatible with Python 2.7 scripts. But we need Jython for a project and nbtlib is an important part of the whole thing.

Everything works fine with Python 3. Which is good because our project basically consists of two parts. A standalone version and a plugin version for Spigot. However, the plugin version uses Jython and that is where problems arise. Our Script works fine until nbtlib has to be loaded.

**Comment by danielgran** [comment]
this lib is intrinsically written to support modern python versions.
Thus, support for python 2.7 is very unlikely.
I see that as closed.

**Comment by Happy2018new** [comment]
I suggest you find or write a **NBT** library which could support **Jython**, or move your work to modern **Python** versions, such as `3.10`.

**Comment by CptGummiball** [comment]
Thank you for the suggestion! Unfortunately, Jython currently only supports Python 2, which has made it challenging to work with. However, due to these difficulties, I have decided to take an alternative approach and have completely reimplemented my project in Java instead of using Python + Java.

**Comment by danielgran** [comment]
> Thank you for the suggestion! Unfortunately, Jython currently only supports Python 2, which has made it challenging to work with. However, due to these difficulties, I have decided to take an alternative approach and have completely reimplemented my project in Java instead of using Python + Java.

Sounds like a clean solution! Kudos!
