### ISSUE TITLE
Remaining support for 1.13

### ISSUE THREAD

**Issue by Arcensoth** [vberlier/nbtlib#2]
I saw that whitespace and case-agnostic prefixes were taken care of recently. 👍 I'll make note of any remaining 1.13 issues here seeing as you're active and able to implement them into the official repo.

Remaining issues for 1.13 support:

1. Something important to note is that whitespace was not valid (in SNBT) until 1.13, so you may wish to either (1) add a parameter to the parser or (2) create a separate branch for legacy (1.12 and prior) support (or vice-versa).
2. Long arrays are now a thing (apparently part of the new region file format), so probably `[L` should be added to the list of tokens and parsed accordingly.

I think that takes care of everything but there may still be changes before 1.13 is fully released.

**Comment by vberlier** [comment]
Thanks for the heads-up!

From my understanding, the changes made to SNBT in 1.13 are backward-compatible. 1.13 nbt literals use a superset of the 1.12 grammar. This means that the changes to the parser won't break compatibility with 1.12 so I think it's fine to leave it as it is.

I didn't know about long arrays though, I'll try to implement them ASAP.

**Comment by vberlier** [comment]
Alright, I added long arrays. I think I'm going to leave the issue open until 1.13 comes out in case anything else changes.

**Comment by vberlier** [comment]
Looks like everything is fine with 1.13.
