### ISSUE TITLE
Help with Minecraft Region Data

### ISSUE THREAD

**Issue by Worf2340** [vberlier/nbtlib#32]
Hi, I saw your comment [here](https://github.com/vberlier/nbtlib/issues/1) on extracting minecraft chunk data to be processed by nbtlib. You said to "extract the nbt regions from the .mca files yourself and feed them to nbtlib manually". I am trying to write a script to process entity data from a region file, but can't figure out how to extract the nbt regions from the file in python. Would you be able to help me out?

Thanks.

**Comment by ch-yx** [comment]
issue #16

**Comment by Worf2340** [comment]
Wow, thanks! That's pretty much exactly what I was looking for.
