### ISSUE TITLE
Implement nbt paths?

### ISSUE THREAD

**Issue by vberlier** [vberlier/nbtlib#34]
First mentioned [here](https://github.com/vberlier/nbtlib/issues/29#issuecomment-513543764). Link to [wiki reference](https://minecraft.gamepedia.com/Commands/data#NBT_path).

I think it would be neat if it could look a bit like this:

```python
p = Path('foo.bar[0]."A [crazy name]!".baz')
some_compound_tag[p]

assert Path()['foo']['bar'][0]['A [crazy name]!']['baz'] == p
assert str(p) == 'foo.bar[0]."A [crazy name]!".baz'
assert p.parent == Path('foo.bar[0]')['A [crazy name]!']
assert p.parts == ('foo', 'bar', 0, 'A [crazy name]!', 'baz')
assert p.stem == Path('foo.bar[0]."A [crazy name]!"')
assert p.name == 'baz'
```

Ideally these would be immutable, and maybe inherit directly from `str` or `tuple`.

**Comment by ch-yx** [comment]
I was reading minecraft source code just now.
It seems that un-quoted keys name can contain any character but 
` space " [ ] { } .`

and can only be quoted by double quote mark.


And.Please note that there is a WAI behaviour:
bugs.mojang.com/browse/MC-139625


Please note its comments too.some of comments are made by mojang.

**Comment by ch-yx** [comment]
emmmmm what do you think?
- [ ] `Path('a.b{d:"e"}.c.[][7]').parts==("a",("b",{"d":"e"}),"c",None,7)`
or
- [ ] `Path('a.b{d:"e"}.c.[][7]').parts==(("a",),("b",{"d":"e"}),("c",),None,7)`

should `Path('{}').parts==((None,{}),)` ?

**Comment by ch-yx** [comment]
I just wrote a parser.
```
>>> import nbtlib.path
>>> nbtlib.path.parser("a.b{}.c[].d[1]")
<generator object parser at 0x000002451EC15048>
>>> *_,
(('a', None), ('b', Compound({})), ('c', None), None, ('d', None), 1)
>>> *nbtlib.path.parser("a.b{}.c[].d[1]"),
(('a', None), ('b', Compound({})), ('c', None), None, ('d', None), 1)
>>> *nbtlib.path.parser("a.b{}.c[].d.[1]."),
(('a', None), ('b', Compound({})), ('c', None), None, ('d', None), 1)
>>> *nbtlib.path.parser('a.b{}.c[].d.[1]."a.b.c.s{}"[-3]'),
(('a', None), ('b', Compound({})), ('c', None), None, ('d', None), 1, ('a.b.c.s{}', None), -3)
>>> *nbtlib.path.parser('a.b{}.c[].d.[1]."a.b.ccc.s{}"[-3]'),
(('a', None), ('b', Compound({})), ('c', None), None, ('d', None), 1, ('a.b.ccc.s{}', None), -3)
>>> *nbtlib.path.parser('a.b{}.c[].d.[1]."a.b.c\\"c\\\\c.s{}"[-3]'),
(('a', None), ('b', Compound({})), ('c', None), None, ('d', None), 1, ('a.b.c"c\\c.s{}', None), -3)
>>> 
```
I'm going to implement some method of that object.

**Comment by ch-yx** [comment]
:smile:
```
>>> np()["2"][3]["2\\3\"4.4"][nbtlib.Compound({"a":nbtlib.String("5")})][nbtlib.Compound({"b":nbtlib.String("6")})]
NBT_Path(2.[3]."2\\3\"4.4"{a: "5", b: "6"}.)

>>> np(r'2.[3]."2\\3\"4.4"{a: "5", b: "6"}')
NBT_Path(2.[3]."2\\3\"4.4"{a: "5", b: "6"}.)

```

**Comment by ch-yx** [comment]
I have Implemented nbt paths and its methods.
but it need optimizing.

I have implemented `attach parts parent name str repr join match(NBT) ` and a small parser.

https://github.com/vberlier/nbtlib/pull/35

**Comment by vberlier** [comment]
You're fast! I'm going to check it out as soon as possible but I'm wondering why the bug you mentioned would be related to this. I mean the compound literal isn't part of the path itself, right?

In my mind, the path api would simply make it possible to access deeply nested values in nbt structures and provide a seamless way to generate new path strings. We could also implement a few ways of validating a path against nbt data or schemas but other than that I don't think there would be a lot to it.

```python
path = Path('foo[0].bar')
data = parse_nbt('{foo: [{bar: "Hello, world!"}]}')

# Access deep values with indexing
assert data[path] == 'Hello, world!'

# Manipulate the path (.parent and indexing)
assert path.parent['spam'][Path('egg[0]')] == 'foo[0].spam.egg[0]'

# Maybe also add something to check if the selected field exists
assert data.get(path) != None
assert path in data

# Would be nice to make it work with schemas too
DataSchema = schema('DataSchema', {'foo': List[schema('Entry', {'bar': String})]})
assert path in DataSchema
```

**Comment by ch-yx** [comment]
But,I have already  implemented compound literal in the path object......
add that **right after** a key's name to make sure it has some key-value pair....
just like in minecraft commands.

I used `-` to join 2 path together（maybe I should change to "|"？）,and use `[]` to attach something to a path.
I use `NBT_Path().match(`some nbt`)` to test... return a list of all matched NBT object.


I did not come up with `in` you just said..I will probably write that soon

**Comment by ch-yx** [comment]
You can do that already：（maybe I should change "-"to "|"？）
```
>>> path = nbtlib.path.NBT_Path('foo[0].bar')
>>> data = nbtlib.parse_nbt('{foo: [{bar: "Hello, world!"}]}')
>>> path.parent
NBT_Path('foo.[0].')
>>> path.parent-"egg[0]"                        #join
NBT_Path('foo.[0].egg.[0].')
>>> path.match(data)                                  #match NBT
[String('Hello, world!')]
>>> path.parent-"egg[0]"==path.parent["egg"][0]                 #attach
True
>>> str(path.parent-"egg[0]")
'foo.[0].egg.[0].'
```

**Comment by ch-yx** [comment]
Could you please have a look at my code? @vberlier

**Comment by vberlier** [comment]
I'm sorry I thought I would be able to check it out before going on
vacation but I didn't have the time. I'm coming back in a couple of weeks
so it's going to have to wait until then :/

**Comment by ch-yx** [comment]
well :/

----------------
I think it is not possible to support schema as it is often unpossible to determine if the path is in the schema.
I will leave it like that.

**Comment by ch-yx** [comment]
and i found there are some difference between my parser and minecraft in some edge cases.
(all vilid spath can be parsed,but some not vilid ones can too)
i will try to fix it.
i dont know if i could do that but i will try.

**Comment by ch-yx** [comment]
I wrote a new parser function and i hope it is better than the older one.:smile:
please replace the old one and check if there any difference between this and minecraft. 


```
def parser(string):
    if string.startswith("{"):
        tag,string=slice_nbt(string)
        yield (None,tag)
    elif string!=".":
        string="."+string
    while string and string!=".":
        
        if string.startswith("[") or string.startswith(".["):#[]
            r=re.match("\.?\[(-?\d+)?\]",string)
            x=r.groups()[0]
            if x:x=int(x)
            string=string[r.end():]
            yield x
        else:
            if string.startswith('."'):#""
                r=re.match(r'\.\"((\\\"|\\\\|[^\\\"])*)\"',string)
                t=r.groups()[0]
                t="\"".join("\\".join(t.split("\\\\")).split("\\\""))
                string=string[r.end():]

            else:
                r=re.match('\\.[^\[\]\{\}\. \"]+',string)
                t=r.group()[1:]
                string=string[r.end():]
            if string.startswith('{'):
                tag,string=slice_nbt(string)
                yield (t,tag)
            else:
                yield (t,None)
```

**Comment by ch-yx** [comment]
I forgot a usage ![{}]
I will fix it asap.

**Comment by ch-yx** [comment]
done

**Comment by vberlier** [comment]
Hello! I'm back from vacation and I took some time to think about the problem. I also reviewed your pull request. I think in the end, mimicking pathlib doesn't really bring any benefit to the API. In pathlib, paths are analogous to strings but here it's more helpful to think of them as collections of object accessors. 

Using this approach I managed to easily implement get, set and delete operations and integrate them into the tag API.

```python
# Regular string key
key = 'spam'
data = parse_nbt('{spam: {egg: 42}}')
print(data[key])  # {egg: 42}

# Same code but the key is a path instead
key = Path('spam.egg')
data = parse_nbt('{spam: {egg: 42}}')
print(data[key])  # 42

# Also works seamlessly for setting and deleting
data[key] = Int(0)
print(data)  # {spam: {egg: 0}}

del data[key]
print(data)  # {spam: {}}

# Also this is what I mean by "collections of accessors"
assert tuple(key) == (NamedKey('spam'), NamedKey('egg'))

assert tuple(Path('hello[0].world{foo: "bar"}')) == (
    NamedKey('hello'), 
    ListIndex(0), 
    NamedKey('world'), 
    CompoundMatch(Compound({'foo': String('bar')}))
)
```

The pull request for this is here feel free to try it out #38. I think the API design and implementation are significantly better than what I originally had in mind.
