### ISSUE TITLE
path

### ISSUE THREAD

**Issue by ch-yx** [vberlier/nbtlib#47]
`parse_nbt("[[{a:2}],[3b]]")[path("[].[].a")]`

raise `TypeError `instead of `IndexError`.

I guess that there may be more bugs like that....😞

**Comment by vberlier** [comment]
Good catch! Just fixed it in 1.6.3. Now `parse_nbt("[[{a:2}],[3b]]")[path("[].[].a")]` returns `Int(2)`, just like in Minecraft.
