### ISSUE TITLE
 serialize_tag, python 3.8

### ISSUE THREAD

**Issue by ch-yx** [vberlier/nbtlib#61]
as we have come to serialize_tag, I do some testing and found something wrong.
`str(nbtlib.Byte(4))    ==   'Byte(4)b'`
`int.__str__(nbtlib.Byte(4))      ==  'Byte(4)'`

https://github.com/vberlier/nbtlib/blob/0b454b7c24b0e2711a7c709493015901a3400ce4/nbtlib/literal/serializer.py#L128-L131

\#probably due to python 3.8 ?

-------------

yes,it is.

`float.__str__ is int.__str__ is object.__str__`    ==>true

even ` int.__str__(4.0)` is accepted now.

-----------------

python 3.8 :

bpo-36793: Removed __str__ implementations from builtin types bool, int, float, complex and few classes from the standard library. They now inherit __str__() from object.

https://github.com/python/cpython/commit/96aeaec64738b730c719562125070a52ed570210

_Originally posted by @ch-yx in https://github.com/vberlier/nbtlib/issues/1#issuecomment-567559128_

**Comment by vberlier** [comment]
Yeah I actually just fixed this #59, thanks for pointing it out :)
