### ISSUE TITLE
The literal parser behaves differently from Minecraft in some edge cases

### ISSUE THREAD

**Issue by ch-yx** [vberlier/nbtlib#7]
nbtlib.parse_nbt("{a:4000b}") return Compound({'a': Byte(4000)})
but in minecraft command ,
it will be Compound({'a': String('4000b')})

**Comment by vberlier** [comment]
Fixed in 841030a6ff37089db48f9ad032c57209e04c9c25. I'll make a release later with several other fixes.

**Comment by ch-yx** [comment]
will it support .mca files？

**Comment by vberlier** [comment]
Not really. `nbtlib` focuses on implementing generic nbt utilities and even though `.mca` files contain nbt data, they're a file format of their own. This is out of the scope of this project but you can still use `nbtlib` to parse the nbt sections of `.mca` files.

**Comment by vberlier** [comment]
Closing the issue as the fix is now in release 1.3.0.

**Comment by ch-yx** [comment]
I just found that minecraft falls back to string if it is not an integer but end up with a integer type suffix as well.
here are some examples:
3.3s
4e-3l
4e3l
03b

**Comment by vberlier** [comment]
Okay so it seems like there's several things that I'll need to take into account:

- Parsing an integer tag should fall back to string if the constructor raises a ValueError
- Include scientific notation in the grammar for floating point tags
- Adjust the grammar such that integer tags can't start with a 0

**Comment by vberlier** [comment]
All of these should now be fixed as of bca40bc7df280d79f162f2ec0c5c41e4f46709c9.

**Comment by vberlier** [comment]
Just released v1.4.5 with the three fixes, closing the issue.

**Comment by ch-yx** [comment]
https://github.com/vberlier/nbtlib/issues/7#issuecomment-457895173


I just found out that there is a built in OverflowError. Don't need to creat a new one.

**Comment by vberlier** [comment]
Not sure, the built-in [OverflowError](https://docs.python.org/3/library/exceptions.html#OverflowError) is meant to be raised "when the result of an arithmetic operation is too large to be represented". The documentation says it's "sometimes raised for integers that are outside a required range" but only for historical reasons (i.e.: not a recommended practice). I think using a custom error is more appropriate in this case.
