### ISSUE TITLE
there are some thing wrong with escape keys of compounds.

### ISSUE THREAD

**Issue by ch-yx** [vberlier/nbtlib#8]
\>\>\> import nbtlib
\>\>\> print(str(nbtlib.parse_nbt(input())))
 {"jso\\\\n":"t\\\\nest"}
{jso
:"t\\\\nest"}
\>\>\> print(str(nbtlib.parse_nbt(input())))
 {"jso\\\\\\\\n":"t\\\\nest"}
{"jso\\\\\\\\n":"t\\\\nest"}
>>>

**Comment by vberlier** [comment]
Fixed in 97efa25d76bb40316450f01dfb5254949d18e6a4. There shouldn't be any escaping problems anymore.

**Comment by vberlier** [comment]
Closing the issue as the fix is now in release 1.3.1.
