### ISSUE TITLE
Add ability to filter nbt output in `nbt` command

### ISSUE THREAD

**Issue by crabdancing** [vberlier/nbtlib#84]
Would be super useful to be able to filter the output of `nbt` for e.g. `Inventory`. Has a lot of quick and dirty Bash scripting possibilities.

**Comment by vberlier** [comment]
That's a good idea! I'm thinking about adding a positional argument that would let you specify an nbt path.

This would look a bit like this:

```bash
$ nbt -r tests/nbt_files/bigtest.nbt 'Level."listTest (compound)"[{name: "Compound tag #0"}]'
{name: "Compound tag #0", created-on: 1264099775885L}
```

Combined with a new flag that would expose the functionality of the [`unpack()`](https://vberlier.github.io/nbtlib/tags/#nbtlib.tag.Base.unpack) method you could also turn it into json:

```bash
$ nbt -r tests/nbt_files/bigtest.nbt 'Level."listTest (compound)"[0]' --unpack json
{"name": "Compound tag #0", "created-on": 1264099775885}
$ nbt -r tests/nbt_files/bigtest.nbt 'Level."listTest (compound)"[].name' --unpack json
"Compound tag #0"
"Compound tag #1"
$ nbt -r tests/nbt_files/bigtest.nbt 'Level."listTest (compound)"[].name' --unpack
Compound tag #0
Compound tag #1
```

What do you think?

**Comment by crabdancing** [comment]
@vberlier That's a good approach! :D

It might also be a good idea to have the option of just recursively searching for a particular tag for a more heuristical approach when the user doesn't know where in the hierarchy it is. :)

**Comment by vberlier** [comment]
I see. Maybe when the path doesn't yield anything we could recurse into the tag hierarchy and try again until something matches. This would be pretty costly if the path specified was absolute and the tag just didn't exist, so the recursive behavior could be enabled by a flag, for when you know the tag exists but not where.

**Comment by crabdancing** [comment]
Yeah, it def shouldn't be the default behavior.

**Comment by vberlier** [comment]
Just added the `--path`, `--unpack` and `--json` options to the cli. I'm planning to add a `--find` option that's going to do the  recursive matching we talked about.

**Comment by vberlier** [comment]
The `--find` option is now in version 1.10 https://github.com/vberlier/nbtlib/releases/tag/v1.10.0

**Comment by crabdancing** [comment]
Awesome! :D Thanks.
