### ISSUE TITLE
Long lists when reading a 'little' byteordered list are scrambled near the end

### ISSUE THREAD

**Issue by RavinMaddHatter** [vberlier/nbtlib#94]
I don't know why this would be, but if i try and load this file via this tool vs a gui tool (NBT studio) i get different results, NBT studio matches the expected format as opened into minecraft bedrock edtion.  The last 2 ints in NBTfile[""]["structure"]["block_indices"][0] should be 70 according to the described format and the NBT studio but i get 1 and 68.

I did page through the parser and i can't see where it would be broken
[test6.zip](https://github.com/vberlier/nbtlib/files/5792062/test6.zip)

**Comment by vberlier** [comment]
Just tried to reproduce but it works fine for me:

```bash
$ nbt -r test6.mcstructure --plain --little --find 'block_indices[0]'    
[0, 1, 1, 1, 1, 1, ..., 2, 2, 2, 1, 1, 1, 1, 70, 70]
```

Edit: Do you have some specific test code that reproduces the problem reliably?

**Comment by RavinMaddHatter** [comment]
I dont know what i was doing wrong. it is working fine now. I must have loaded the wrong file and printed things out of order. 

Thank you for quickly looking at it, Thank you for working on the project, sorry about a bad bug.

**Comment by vberlier** [comment]
No problem :+1:
